In [1]:
# Simple Linear Regression

In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\yashk\Downloads\startup_data.csv")
df.head()

         RND      ADMIN        MKT       STATE     PROFIT
0  165349.20  136897.80  471784.10    New York  192261.83
1  162597.70  151377.59  443898.53  California  191792.06
2  153441.51  101145.55  407934.54     Florida  191050.39
3  144372.41  118671.85  383199.62    New York  182901.99
4  142107.34   91391.77  366168.42     Florida  166187.94

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   RND     50 non-null     float64
 1   ADMIN   50 non-null     float64
 2   MKT     50 non-null     float64
 3   STATE   50 non-null     object
 4   PROFIT  50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB

In [4]:
df.isna().sum()

RND       0
ADMIN     0
MKT       0
STATE     0
PROFIT    0
dtype: int64

In [5]:
df.duplicated().sum()
#Remove duplicates
#df.drop_duplicates()

0

In [6]:
# Seperate X and Y features
#X: Independent feature => RND
#Y:Dependent feature=> PROFIT

In [7]:
X=df[["RND"]]
Y=df[["PROFIT"]]

In [8]:
#There are no missing values nor any duplicated rows in this data
#still we need to add cleaning step(for future data)

In [9]:
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer

In [10]:
pipe = make_pipeline(SimpleImputer(strategy="median")).set_output(transform="pandas")
pipe

Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median'))])

In [11]:
X_pre = pipe.fit_transform(X)
X_pre.head()

         RND
0  165349.20
1  162597.70
2  153441.51
3  144372.41
4  142107.34

In [12]:
# Model Building:Linear Regression
# Equation of line: y = B0+B1x
# B0=> y intercept
# B1 => slope of the line
# ProfitPredicted = B0+B1*RND

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
model = LinearRegression()
model.fit(X,Y)

LinearRegression()

In [15]:
#B0- y intercept
model.intercept_

array([49032.89914125])

In [16]:
#B1- slope of the line
model.coef_

array([[0.85429137]])

In [17]:
# ProfitPredicted = 49032.9+0.854*RND
# RND=0 ProftPredicted = 49032.9
# RND =1 it will increase by 0.854times

In [18]:
Y.head()

      PROFIT
0  192261.83
1  191792.06
2  191050.39
3  182901.99
4  166187.94

In [19]:
Ypreds = model.predict(X)
Ypreds[0:5]

array([[190289.29389289],
       [187938.71118575],
       [180116.65707807],
       [172369.00320589],
       [170433.97345032]])

In [20]:
# Evaluation Metrics
# Mean Squared Error
# Mean Absolute Error
# RMSE
# R2-score

In [21]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [22]:
#mean Squared Error
MSE = mean_squared_error(Y,Ypreds)
#RMSE-Root Mean squared Error
RMSE = MSE**(1/2)
#MAE
MAE = mean_absolute_error(Y,Ypreds)
#R2 score
r2 = r2_score(Y,Ypreds)
print(f"Mean Squared Error:{MSE:.2f}")
print(f"Root Mean Squared Error:{RMSE:.2f}")
print(f"Mean Absolute Error:{MAE:.2f}")
print(f"R2 score:{r2:.2f}")

Mean Squared Error:85120931.33
Root Mean Squared Error:9226.10
Mean Absolute Error:6910.98
R2 score:0.95

In [23]:
# R2 square value is greater than 0.80, we can consider this model for final model building

In [24]:
rnd_sample = [160045,178000,187000,198650]
preds =[]
for x in rnd_sample:
  pred = model.predict([[x]]).round(2)
  preds.append(pred)

C:\Users\yashk\anaconda4\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\yashk\anaconda4\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\yashk\anaconda4\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\yashk\anaconda4\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [25]:
print(preds)

[array([[185757.96]]), array([[201096.76]]), array([[208785.39]]), array([[218737.88]])]

In [26]:

# Train test Split
# rate at which you divide data:
# 100%
# 60% training 40% testing
# 70% training and 30% testing
# 80% training and 20% testing

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
# Train Test split

In [29]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.20,random_state=42)

In [30]:
X_train

          RND
12   93863.75
4   142107.34
37   44069.95
8   120542.52
3   144372.41
6   134615.46
41   27892.92
46    1315.46
47       0.00
15  114523.61
9   123334.88
16   78013.11
24   77044.01
34   46426.07
31   61136.38
0   165349.20
44   22177.74
27   72107.60
33   55493.95
5   131876.90
29   65605.48
11  100671.96
36   28663.76
1   162597.70
21   78389.47
2   153441.51
43   15505.73
35   46014.02
23   67532.53
40   28754.33
10  101913.08
22   73994.56
18   91749.16
49       0.00
20   76253.86
7   130298.13
42   23640.93
14  119943.24
28   66051.52
38   20229.59

In [31]:
#Train model

In [32]:
model = LinearRegression()
model.fit(X_train,Y_train)

LinearRegression()

In [33]:
#Prediction
y_pred = model.predict(X_test)

In [34]:
#mean Squared Error
MSE = mean_squared_error(Y_test,y_pred)
#RMSE-Root Mean squared Error
RMSE = MSE**(1/2)
#MAE
MAE = mean_absolute_error(Y_test,y_pred)
#R2 score
r2 = r2_score(Y_test,y_pred)
print(f"Mean Squared Error:{MSE:.2f}")
print(f"Root Mean Squared Error:{RMSE:.2f}")
print(f"Mean Absolute Error:{MAE:.2f}")
print(f"R2 score:{r2:.2f}")

Mean Squared Error:59510962.81
Root Mean Squared Error:7714.33
Mean Absolute Error:6077.36
R2 score:0.93